name: Build & Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    env:
      Configuration: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v4

      - name: Restore NuGet
        run: nuget restore ExportTelegramContacts.sln

      - name: Build
        run: msbuild ExportTelegramContacts.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Create ZIP
        run: |
          powershell Compress-Archive `
          -Path ExportTelegramContacts/bin/Release/* `
          -DestinationPath ExportTelegramContacts-portable.zip

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ExportTelegramContacts-portable.zip
            ExportTelegramContacts/bin/Release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
